import type { Metadata } from "next";
import { Client } from "./client";
import "@/styles/globals.css";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {
  const { locale } = await params;
  return (
    <html lang={locale} suppressHydrationWarning className="font-sans">
      <body>
        <NextIntlClientProvider>
          <Client>{children}</Client>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
